[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
releaseCommand = ""
restartPolicyType = "on_failure"

[variables]
NODE_ENV = "production" 